### ISSUE TITLE
Promster hapi plugin throws errors on requests

### ISSUE THREAD

**Issue by Stmu** [tdeekens/promster#160]
**Describe the bug**
The hapi plugin throws errors on every request with current version (2.2.6) and hapi 18.3

**To Reproduce**
please look at additional context.

**Expected behavior**
no errors are fine

**Screenshots**

**Additional context**

The handler onResponseHandler uses the reply argument, but the hapi api does not have this argument in the signature ([Hapi-API](https://hapijs.com/api#-response-event)). I think the return statement is not needed, but i'am not sure.

UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'continue' of undefined
    at Object.onResponseHandler [as listener] (/app/node_modules/@promster/hapi/modules/plugin/plugin.js:75:67)
    at module.exports.internals.Podium.internals.Podium.emit (/app/node_modules/podium/lib/index.js:228:107)
    at Request._finalize (/app/node_modules/hapi/lib/request.js:447:27)
    at Request._reply (/app/node_modules/hapi/lib/request.js:391:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by tdeekens** [comment]
Thanks. Will check soon.

**Comment by tdeekens** [comment]
Thanks for the detailed bug report. I was able to reproduce and fixed it inn @promster/hapi@2.2.7. I'll close the issue. Feel free to re-open given the issue persists.
