### ISSUE TITLE
Can't create middleware twice

### ISSUE THREAD

**Issue by Ghazgkull** [tdeekens/promster#200]
**Describe the bug**
Calling promster.createMiddleware() twice results in an error being thrown: `A metric with the name up has already been registered.`

**To Reproduce**

1. Create a simple test.js file:
```
const promster = require('@promster/express');
promster.createMiddleware({});
promster.createMiddleware({});
```
2. Run it: `node test.js`

The following error occurs:
```
/path/to/node_modules/prom-client/lib/registry.js:85
			throw new Error(
			^

Error: A metric with the name up has already been registered.
    at Registry.registerMetric (/Users/jburn9/projects/eap/dam-common/node_modules/prom-client/lib/registry.js:85:10)
    at Gauge.config.registers.forEach.registryInstance (/Users/jburn9/projects/eap/dam-common/node_modules/prom-client/lib/gauge.js:76:21)
    at Array.forEach (<anonymous>)
    at new Gauge (/Users/jburn9/projects/eap/dam-common/node_modules/prom-client/lib/gauge.js:75:20)
    at getDefaultMetrics (/Users/jburn9/projects/eap/dam-common/node_modules/@promster/metrics/modules/create-metric-types/create-metric-types.js:80:7)
    at createMetricTypes (/Users/jburn9/projects/eap/dam-common/node_modules/@promster/metrics/modules/create-metric-types/create-metric-types.js:156:26)
    at Object.createMiddleware (/Users/jburn9/projects/eap/dam-common/node_modules/@promster/express/modules/middleware/middleware.js:30:23)
    at Object.<anonymous> (/Users/jburn9/projects/eap/dam-common/test.js:4:10)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
```

**Additional context**
This isn't particularly a problem at runtime because I only instantiate one of these middleware per service. But it's an issue in unit testing. I want to call a function which instantiates this middleware multiple times to test with different parameters, but I can't because this call blows up.

**Comment by tdeekens** [comment]
Thanks for reporting the issue.

This essentially is not really due to @promster but more to prom-client and a single Prometheus registry underneath. The default registry is used to assign/setup metrics too already has the metric `up` registered. This would happen with any other metric too e.g. a `my_total_foo_count`.

Given the tests would run all in a separate process (e.g. in Jest) this should not be an issue. However, if tests run in one process while all create their own promster middleware this problem arises. That's at least how I understand what happens.

What is you current test setup? What libraries do you use and more specifically how do you test your server with promster and why do you create multiple middlewares?

**Comment by tdeekens** [comment]
Can you give https://github.com/tdeekens/promster/pull/203 a try if this solves it for you?

**Comment by tdeekens** [comment]
Closing due to inactivity.

**Comment by gempain** [comment]
@tdeekens hi ! I tried to register multiple apps with different prefixes, but it doesn't seem to work, so I'd be interested about this issue/pr that you closed.

Here is what I have:

```js
apps.forEach(({ app, label }) => {
    app.use(createMiddleware({
      app: app as any,
      // https://github.com/tdeekens/promster#promstermarblejs
      options: {
        metricPrefix: `${label}`,
      },
    }));
  });
```

Which gives me the following metrics:

```
# HELP app1_process_cpu_user_seconds_total Total user CPU time spent in seconds.
# TYPE app1_process_cpu_user_seconds_total counter
app1_process_cpu_user_seconds_total 0.022797

# HELP app1_process_cpu_system_seconds_total Total system CPU time spent in seconds.
# TYPE app1_process_cpu_system_seconds_total counter
app1_process_cpu_system_seconds_total 0.006456

# HELP app1_process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE app1_process_cpu_seconds_total counter
app1_process_cpu_seconds_total 0.029253

# HELP app1_process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE app1_process_start_time_seconds gauge
app1_process_start_time_seconds 1616059590

# HELP app1_process_resident_memory_bytes Resident memory size in bytes.
# TYPE app1_process_resident_memory_bytes gauge
app1_process_resident_memory_bytes 86024192

# HELP app1_nodejs_eventloop_lag_seconds Lag of event loop in seconds.
# TYPE app1_nodejs_eventloop_lag_seconds gauge
app1_nodejs_eventloop_lag_seconds 0

# HELP app1_nodejs_eventloop_lag_min_seconds The minimum recorded event loop delay.
# TYPE app1_nodejs_eventloop_lag_min_seconds gauge
app1_nodejs_eventloop_lag_min_seconds 0.00933888

# HELP app1_nodejs_eventloop_lag_max_seconds The maximum recorded event loop delay.
# TYPE app1_nodejs_eventloop_lag_max_seconds gauge
app1_nodejs_eventloop_lag_max_seconds 0.012771327

# HELP app1_nodejs_eventloop_lag_mean_seconds The mean of the recorded event loop delays.
# TYPE app1_nodejs_eventloop_lag_mean_seconds gauge
app1_nodejs_eventloop_lag_mean_seconds 0.011255324882051282

# HELP app1_nodejs_eventloop_lag_stddev_seconds The standard deviation of the recorded event loop delays.
# TYPE app1_nodejs_eventloop_lag_stddev_seconds gauge
app1_nodejs_eventloop_lag_stddev_seconds 0.000824442504269196

# HELP app1_nodejs_eventloop_lag_p50_seconds The 50th percentile of the recorded event loop delays.
# TYPE app1_nodejs_eventloop_lag_p50_seconds gauge
app1_nodejs_eventloop_lag_p50_seconds 0.011100159

# HELP app1_nodejs_eventloop_lag_p90_seconds The 90th percentile of the recorded event loop delays.
# TYPE app1_nodejs_eventloop_lag_p90_seconds gauge
app1_nodejs_eventloop_lag_p90_seconds 0.012500991

# HELP app1_nodejs_eventloop_lag_p99_seconds The 99th percentile of the recorded event loop delays.
# TYPE app1_nodejs_eventloop_lag_p99_seconds gauge
app1_nodejs_eventloop_lag_p99_seconds 0.012697599

# HELP app1_nodejs_active_handles Number of active libuv handles grouped by handle type. Every handle type is C++ class name.
# TYPE app1_nodejs_active_handles gauge
app1_nodejs_active_handles{type="WriteStream"} 2
app1_nodejs_active_handles{type="Socket"} 2
app1_nodejs_active_handles{type="Server"} 3

# HELP app1_nodejs_active_handles_total Total number of active handles.
# TYPE app1_nodejs_active_handles_total gauge
app1_nodejs_active_handles_total 7

# HELP app1_nodejs_active_requests Number of active libuv requests grouped by request type. Every request type is C++ class name.
# TYPE app1_nodejs_active_requests gauge

# HELP app1_nodejs_active_requests_total Total number of active requests.
# TYPE app1_nodejs_active_requests_total gauge
app1_nodejs_active_requests_total 0

# HELP app1_nodejs_heap_size_total_bytes Process heap size from Node.js in bytes.
# TYPE app1_nodejs_heap_size_total_bytes gauge
app1_nodejs_heap_size_total_bytes 63700992

# HELP app1_nodejs_heap_size_used_bytes Process heap size used from Node.js in bytes.
# TYPE app1_nodejs_heap_size_used_bytes gauge
app1_nodejs_heap_size_used_bytes 37687688

# HELP app1_nodejs_external_memory_bytes Node.js external memory size in bytes.
# TYPE app1_nodejs_external_memory_bytes gauge
app1_nodejs_external_memory_bytes 2027782

# HELP app1_nodejs_heap_space_size_total_bytes Process heap space size total from Node.js in bytes.
# TYPE app1_nodejs_heap_space_size_total_bytes gauge
app1_nodejs_heap_space_size_total_bytes{space="read_only"} 151552
app1_nodejs_heap_space_size_total_bytes{space="new"} 33554432
app1_nodejs_heap_space_size_total_bytes{space="old"} 23478272
app1_nodejs_heap_space_size_total_bytes{space="code"} 622592
app1_nodejs_heap_space_size_total_bytes{space="map"} 1314816
app1_nodejs_heap_space_size_total_bytes{space="large_object"} 4530176
app1_nodejs_heap_space_size_total_bytes{space="code_large_object"} 49152
app1_nodejs_heap_space_size_total_bytes{space="new_large_object"} 0

# HELP app1_nodejs_heap_space_size_used_bytes Process heap space size used from Node.js in bytes.
# TYPE app1_nodejs_heap_space_size_used_bytes gauge
app1_nodejs_heap_space_size_used_bytes{space="read_only"} 150392
app1_nodejs_heap_space_size_used_bytes{space="new"} 9032264
app1_nodejs_heap_space_size_used_bytes{space="old"} 22492752
app1_nodejs_heap_space_size_used_bytes{space="code"} 352992
app1_nodejs_heap_space_size_used_bytes{space="map"} 1185696
app1_nodejs_heap_space_size_used_bytes{space="large_object"} 4479792
app1_nodejs_heap_space_size_used_bytes{space="code_large_object"} 2880
app1_nodejs_heap_space_size_used_bytes{space="new_large_object"} 0

# HELP app1_nodejs_heap_space_size_available_bytes Process heap space size available from Node.js in bytes.
# TYPE app1_nodejs_heap_space_size_available_bytes gauge
app1_nodejs_heap_space_size_available_bytes{space="read_only"} 0
app1_nodejs_heap_space_size_available_bytes{space="new"} 7726520
app1_nodejs_heap_space_size_available_bytes{space="old"} 914672
app1_nodejs_heap_space_size_available_bytes{space="code"} 2400
app1_nodejs_heap_space_size_available_bytes{space="map"} 126064
app1_nodejs_heap_space_size_available_bytes{space="large_object"} 0
app1_nodejs_heap_space_size_available_bytes{space="code_large_object"} 0
app1_nodejs_heap_space_size_available_bytes{space="new_large_object"} 16758784

# HELP app1_nodejs_version_info Node.js version info.
# TYPE app1_nodejs_version_info gauge
app1_nodejs_version_info{version="v14.16.0",major="14",minor="16",patch="0"} 1

# HELP app1_nodejs_gc_duration_seconds Garbage collection duration by kind, one of major, minor, incremental or weakcb.
# TYPE app1_nodejs_gc_duration_seconds histogram

# HELP app1_up 1 = up, 0 = not up
# TYPE app1_up gauge
app1_up 0

# HELP app1_nodejs_gc_runs_total Count of total garbage collections.
# TYPE app1_nodejs_gc_runs_total counter

# HELP app1_nodejs_gc_pause_seconds_total Time spent in GC Pause in seconds.
# TYPE app1_nodejs_gc_pause_seconds_total counter

# HELP app1_nodejs_gc_reclaimed_bytes_total Total number of bytes reclaimed by GC.
# TYPE app1_nodejs_gc_reclaimed_bytes_total counter

# HELP app1_http_request_duration_seconds The HTTP request latencies in seconds.
# TYPE app1_http_request_duration_seconds histogram

# HELP app1_http_requests_total The total HTTP requests.
# TYPE app1_http_requests_total counter

# HELP app2_up 1 = up, 0 = not up
# TYPE app2_up gauge
app2_up 1

# HELP app2_nodejs_gc_runs_total Count of total garbage collections.
# TYPE app2_nodejs_gc_runs_total counter

# HELP app2_nodejs_gc_pause_seconds_total Time spent in GC Pause in seconds.
# TYPE app2_nodejs_gc_pause_seconds_total counter

# HELP app2_nodejs_gc_reclaimed_bytes_total Total number of bytes reclaimed by GC.
# TYPE app2_nodejs_gc_reclaimed_bytes_total counter

# HELP app2_http_request_duration_seconds The HTTP request latencies in seconds.
# TYPE app2_http_request_duration_seconds histogram

# HELP app2_http_requests_total The total HTTP requests.
# TYPE app2_http_requests_total counter
```

As you can see, `app2_` metrics aren't populated.
